s=set()
n=input("Enter eight num: ")
s.add(int(n))
n=input("Enter eight num: ")
s.add(int(n))
n=input("Enter eight num: ")
s.add(int(n))
n=input("Enter eight num: ")
s.add(int(n))
n=input("Enter eight num: ")
s.add(int(n))
n=input("Enter eight num: ")
s.add(int(n))
n=input("Enter eight num: ")
s.add(int(n))
n=input("Enter eight num: ")
s.add(int(n))

print(s)