d={}
n1=input("Enter Name:")
s1=input("Enter Subject:")
print(n1)
print(s1)
d.update({n1:s1})
n1=input("Enter Name:")
s1=input("Enter Subject:")
print(n1)
print(s1)
d.update({n1:s1})
n1=input("Enter Name:")
s1=input("Enter Subject:")
print(n1)
print(s1)
d.update({n1:s1})
n1=input("Enter Name:")
s1=input("Enter Subject:")
print(n1)
print(s1)
d.update({n1:s1})

print(d)